### ISSUE TITLE
Cannot install deb in ubuntu 14.04

### ISSUE THREAD

**Issue by POMATu** [patjak/mba6x_bl#45]
```
user@mac:~$ dpkg -i mba6xbl-dkms_1.0.0_all.deb 
dpkg: error: requested operation requires superuser privilege
user@macbuntu:~$ sudo dpkg -i mba6xbl-dkms_1.0.0_all.deb 
Selecting previously unselected package mba6xbl-dkms.
(Reading database ... 226699 files and directories currently installed.)
Preparing to unpack mba6xbl-dkms_1.0.0_all.deb ...
Unpacking mba6xbl-dkms (1.0.0) ...
Setting up mba6xbl-dkms (1.0.0) ...

Loading tarball for mba6xbl-1.0.0
Loading /var/lib/dkms/mba6xbl/1.0.0/4.1.0-040100-generic/x86_64...

DKMS: ldtarball completed.

Creating symlink /var/lib/dkms/mba6xbl/1.0.0/source ->
                 /usr/src/mba6xbl-1.0.0

DKMS: add completed.
First Installation: checking all kernels...
Building only for 4.2.0-35-generic
Building for architecture x86_64
Building initial module for 4.2.0-35-generic
ERROR (dkms apport): unable to determine source package for mba6xbl-dkms
Error! Bad return status for module build on kernel: 4.2.0-35-generic (x86_64)
Consult /var/lib/dkms/mba6xbl/1.0.0/build/make.log for more information.
user@mac:~$ cat /var/lib/dkms/mba6xbl/1.0.0/build/make.log 
DKMS make.log for mba6xbl-1.0.0 for kernel 4.2.0-35-generic (x86_64)
Tue Apr 19 15:54:52 MSK 2016
make -C /lib/modules/4.2.0-35-generic/build M=/var/lib/dkms/mba6xbl/1.0.0/build modules
make[1]: Entering directory `/usr/src/linux-headers-4.2.0-35-generic'
  CC [M]  /var/lib/dkms/mba6xbl/1.0.0/build/mba6x_bl.o
/var/lib/dkms/mba6xbl/1.0.0/build/mba6x_bl.c: In function 'platform_probe':
/var/lib/dkms/mba6xbl/1.0.0/build/mba6x_bl.c:336:2: error: implicit declaration of function 'acpi_video_dmi_promote_vendor' [-Werror=implicit-function-declaration]
  acpi_video_dmi_promote_vendor();
  ^
cc1: some warnings being treated as errors
make[2]: *** [/var/lib/dkms/mba6xbl/1.0.0/build/mba6x_bl.o] Error 1
make[1]: *** [_module_/var/lib/dkms/mba6xbl/1.0.0/build] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-4.2.0-35-generic'
make: *** [all] Error 2

```

**Comment by POMATu** [comment]
I compiled module from git sources and it works good. It seems that just dkms package is broken.

**Comment by patjak** [comment]
Closing since not updated in a while. Hopefully the dkms package works now.
